### ISSUE TITLE
ImportError: No module named _api

### ISSUE THREAD

**Issue by extralucide** [formalmethods/intrepid#4]
Hi
When I try to import intrepyd
I obtain the following exception in the module api.py:
  File "D:\pymbd\floatvsreal\intrepyd\api.py", line 20, in swig_import_helper
    import _api
ImportError: No module named _api

**Comment by robertobruttomesso** [comment]
Hi extralucide,

sorry for the late reply. From the file path I assume you are under windows.
the module _api is enclosed in the dll with path "intrepyd/libs/win64/_api.pyd". It looks like that this dll is not reachable by the windows. Have you installed intrepyd via "pip" or manually ?
